/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Alterar;

import Exceptions.NullUserException;
import Model.Session;
import Principal.Login;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import school.ControlarPropriedade;

/**
 *
 * @author Misael
 */
public class AlterarTemaDoSistemaJ extends javax.swing.JFrame {

    /**
     * Creates new form AlterarTemaDoSistemaJ
     */
    public AlterarTemaDoSistemaJ() {
        initComponents();

        GrupoTema.add(BTNimbus);
        GrupoTema.add(BTSistema);
        GrupoTema.add(BTCerulean);
        GrupoTema.add(BTRaven);
        setSelected();
    }

    private void setSelected() {
        try {
            switch (ControlarPropriedade.lerPropriedade()) {
                case "Nimbus":
                    BTNimbus.setSelected(true);
                    break;
                case "Sistema":
                    BTSistema.setSelected(true);
                    break;
                case "Raven":
                    BTRaven.setSelected(true);
                    break;
                case "Cerulean":
                    BTCerulean.setSelected(true);
                    break;
            }
        } catch (IOException ex) {
            Logger.getLogger(AlterarTemaDoSistemaJ.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoTema = new javax.swing.ButtonGroup();
        ButtonAlterar = new javax.swing.JButton();
        BTNimbus = new javax.swing.JRadioButton();
        BTSistema = new javax.swing.JRadioButton();
        BTCerulean = new javax.swing.JRadioButton();
        BTRaven = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonAlterar.setText("Alterar");
        ButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAlterarActionPerformed(evt);
            }
        });

        BTNimbus.setText("Nimbus");

        BTSistema.setText("Padrão do Sistema");

        BTCerulean.setText("Cerulean");

        BTRaven.setText("Raven");

        jPanel1.setBackground(new java.awt.Color(0, 119, 36));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alterar o tema do sistema");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonAlterar)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNimbus)
                    .addComponent(BTRaven)
                    .addComponent(BTCerulean)
                    .addComponent(BTSistema))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(BTSistema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNimbus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTCerulean)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTRaven)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(ButtonAlterar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAlterarActionPerformed
        // TODO add your handling code here:
        String selecionado = getSelectedButton();
        try {
            ControlarPropriedade.escreverPropriedade(selecionado);
        } catch (IOException ex) {
            Logger.getLogger(AlterarTemaDoSistemaJ.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.dispose();
        JOptionPane.showMessageDialog(null, "Entre no sistema novamente para ver as alterações");
        try {
            new Principal.Principal().setVisible(true);
        } catch (NullUserException ex) {
            Logger.getLogger(AlterarTemaDoSistemaJ.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ButtonAlterarActionPerformed
    public String getSelectedButton() {
        if (BTNimbus.isSelected()) {
            return "Nimbus";
        }
        if (BTSistema.isSelected()) {
            return "Sistema";
        }
        if (BTCerulean.isSelected()) {
            return "Cerulean";
        }
        if(BTRaven.isSelected()){
        return "Raven";
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarTemaDoSistemaJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarTemaDoSistemaJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarTemaDoSistemaJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarTemaDoSistemaJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarTemaDoSistemaJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BTCerulean;
    private javax.swing.JRadioButton BTNimbus;
    private javax.swing.JRadioButton BTRaven;
    private javax.swing.JRadioButton BTSistema;
    private javax.swing.JButton ButtonAlterar;
    private javax.swing.ButtonGroup GrupoTema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
