/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import DAO.Conexao;
import DAO.DAOtest;
import DAO.UsuarioDAO;
import Model.Session;
import Model.Usuario;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import org.pushingpixels.substance.api.skin.SubstanceCremeCoffeeLookAndFeel;
import school.ControlarPropriedade;
import school.PrepareIcon;

/**
 *
 * @author adria
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        inicializar();
        initComponents();
        this.setIconImage(PrepareIcon.getInstance().getImage());
        //586,283
        this.setSize(550, 280);
        this.setResizable(false);
        try {
            ControlarPropriedade.lerPropriedade();
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    boolean primeiroLogin = false;

    private void inicializar() {

        if (DAOtest.testarCadastroTipoUsuario()) {
            DAOtest.cadastrarTiposdeUsuarios();
            inicializar();
        }
        if (DAOtest.testarCadastroDeDificuldade()) {
            DAOtest.cadastrarDificuldades();
            inicializar();

        }
        if (DAOtest.testarCadastroAdmin()) {
            DAOtest.cadastrarADMPadrao();
            inicializar();
            primeiroLogin = true;

        }
//UDM
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PFSenha = new javax.swing.JPasswordField();
        JBEntrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JBSair = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMaximumSize(new java.awt.Dimension(603, 320));
        setMinimumSize(new java.awt.Dimension(603, 320));
        setSize(588,278
        );
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(null);

        PFSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PFSenhaKeyReleased(evt);
            }
        });
        getContentPane().add(PFSenha);
        PFSenha.setBounds(60, 170, 260, 40);

        JBEntrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JBEntrar.setText("Entrar");
        JBEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(JBEntrar);
        JBEntrar.setBounds(230, 220, 90, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/padlock.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 170, 40, 40);

        JBSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JBSair.setText("Sair");
        JBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSairActionPerformed(evt);
            }
        });
        getContentPane().add(JBSair);
        JBSair.setBounds(60, 220, 90, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user (3).png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 110, 50, 32);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de Geração de Provas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 30, 330, 40);

        TFUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFUsuarioKeyReleased(evt);
            }
        });
        getContentPane().add(TFUsuario);
        TFUsuario.setBounds(60, 110, 260, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/colegio.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 20, 240, 250);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-8, 0, 640, 300);

        setSize(new java.awt.Dimension(603, 336));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEntrarActionPerformed
        // TODO add your handling code here:
        Logar();
    }//GEN-LAST:event_JBEntrarActionPerformed
    private void Logar() {
        String usuario = TFUsuario.getText();
        String senha = String.valueOf(PFSenha.getPassword());

        if (usuario.equals("") || senha.equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Sistema de Provas", JOptionPane.ERROR_MESSAGE);
        } else {

            Session.getInstance().setUsuario(new UsuarioDAO().Logar(usuario, senha));
            // System.out.println(Session.getInstance().getUsuario().getNome());
            if (Session.getInstance().getUsuario() != null) {
                Principal principal = new Principal(primeiroLogin);
                principal.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Login não autorizado", "Sistema de Provas ", JOptionPane.ERROR_MESSAGE);
            }
        }

    }
    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        keyPressedOrReleased(evt);
    }//GEN-LAST:event_formKeyReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        keyPressedOrReleased(evt);
    }//GEN-LAST:event_formKeyPressed

    private void PFSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PFSenhaKeyReleased
        // TODO add your handling code here:
        keyPressedOrReleased(evt);
    }//GEN-LAST:event_PFSenhaKeyReleased

    private void TFUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFUsuarioKeyReleased
        // TODO add your handling code here:
        keyPressedOrReleased(evt);
    }//GEN-LAST:event_TFUsuarioKeyReleased

    private void JBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JBSairActionPerformed
    private void keyPressedOrReleased(KeyEvent evt) {
        if (10 == evt.getKeyCode()) {
            Logar();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    switch (ControlarPropriedade.lerPropriedade()) {
                        case "Nimbus":
                            javax.swing.UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
                            break;
                        case "Sistema":
                            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                            break;
                        case "Raven":
                            javax.swing.UIManager.setLookAndFeel("org.pushingpixels.substance.api.skin.SubstanceRavenLookAndFeel");
                            break;
                        case "Cerulean":
                            javax.swing.UIManager.setLookAndFeel("org.pushingpixels.substance.api.skin.SubstanceCeruleanLookAndFeel");
                            break;

                        //javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    }

                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException | IOException ex) {
                    java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }

                new Login().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBEntrar;
    private javax.swing.JButton JBSair;
    private javax.swing.JPasswordField PFSenha;
    private javax.swing.JTextField TFUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
