-- MySQL Script generated by MySQL Workbench
-- Fri Jun  8 23:00:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema prova
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prova
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prova` DEFAULT CHARACTER SET utf8 ;
USE `prova` ;

-- -----------------------------------------------------
-- Table `prova`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prova`.`disciplina` (
  `idDisciplina` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeMateria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDisciplina`),
  UNIQUE INDEX `nomeMateria_UNIQUE` (`nomeMateria` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `prova`.`tipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prova`.`tipoUsuario` (
  `idtipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prova`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prova`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `tipoUsuarioId` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_tipoUsuario1_idx` (`tipoUsuarioId` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  CONSTRAINT `fk_usuario_tipoUsuario1`
    FOREIGN KEY (`tipoUsuarioId`)
    REFERENCES `prova`.`tipoUsuario` (`idtipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prova`.`ProfessorDisciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prova`.`ProfessorDisciplina` (
  `idProfDisc` INT NOT NULL AUTO_INCREMENT,
  `idDisciplina` INT(11) NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idProfDisc`),
  INDEX `fk_professor_has_disciplina_disciplina1_idx` (`idDisciplina` ASC),
  INDEX `fk_professordisciplina_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_professor_has_disciplina_disciplina1`
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `prova`.`disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professordisciplina_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `prova`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `prova`.`Prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prova`.`Prova` (
  `idProva` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idProfessor` INT NOT NULL,
  PRIMARY KEY (`idProva`),
  INDEX `fk_Prova_usuario1_idx` (`idProfessor` ASC),
  CONSTRAINT `fk_Prova_usuario1`
    FOREIGN KEY (`idProfessor`)
    REFERENCES `prova`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prova`.`Assunto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prova`.`Assunto` (
  `idAssunto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idDisciplina` INT(11) NOT NULL,
  PRIMARY KEY (`idAssunto`),
  INDEX `fk_Assunto_disciplina1_idx` (`idDisciplina` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  CONSTRAINT `fk_Assunto_disciplina1`
    FOREIGN KEY (`idDisciplina`)
    REFERENCES `prova`.`disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prova`.`dificuldade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prova`.`dificuldade` (
  `iddificuldade` INT NOT NULL AUTO_INCREMENT,
  `dificuldade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddificuldade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prova`.`questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prova`.`questao` (
  `idQuestao` INT(11) NOT NULL AUTO_INCREMENT,
  `Enunciado` VARCHAR(1000) NOT NULL,
  `resposta` VARCHAR(500) NULL DEFAULT NULL,
  `idAssunto` INT NOT NULL,
  `iddificuldade` INT NOT NULL,
  PRIMARY KEY (`idQuestao`),
  INDEX `fk_questao_Assunto1_idx` (`idAssunto` ASC),
  INDEX `fk_questao_dificuldade1` (`iddificuldade` ASC),
  CONSTRAINT `fk_questao_Assunto1`
    FOREIGN KEY (`idAssunto`)
    REFERENCES `prova`.`Assunto` (`idAssunto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questao_dificuldade1`
    FOREIGN KEY (`iddificuldade`)
    REFERENCES `prova`.`dificuldade` (`iddificuldade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `prova`.`Prova_Questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prova`.`Prova_Questao` (
  `questao_idQuestao` INT(11) NOT NULL,
  `Prova_idProva` INT NOT NULL,
  `numQuestao` INT NOT NULL,
  PRIMARY KEY (`questao_idQuestao`, `Prova_idProva`),
  INDEX `fk_questao_has_Prova_Prova1_idx` (`Prova_idProva` ASC),
  INDEX `fk_questao_has_Prova_questao1_idx` (`questao_idQuestao` ASC),
  CONSTRAINT `fk_questao_has_Prova_questao1`
    FOREIGN KEY (`questao_idQuestao`)
    REFERENCES `prova`.`questao` (`idQuestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questao_has_Prova_Prova1`
    FOREIGN KEY (`Prova_idProva`)
    REFERENCES `prova`.`Prova` (`idProva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `prova`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prova`.`itens` (
  `questao_idQuestao` INT(11) NOT NULL,
  `a` VARCHAR(200) NULL DEFAULT NULL,
  `b` VARCHAR(200) NULL DEFAULT NULL,
  `c` VARCHAR(200) NULL DEFAULT NULL,
  `d` VARCHAR(200) NULL DEFAULT NULL,
  `e` VARCHAR(200) NULL DEFAULT NULL,
  `correto` CHAR NOT NULL,
  INDEX `fk_itens_questao1` (`questao_idQuestao` ASC),
  PRIMARY KEY (`questao_idQuestao`),
  CONSTRAINT `fk_itens_questao1`
    FOREIGN KEY (`questao_idQuestao`)
    REFERENCES `prova`.`questao` (`idQuestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
