/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Consultar;

import DAO.AssuntoDAO;
import DAO.DisciplinaDAO;
import Model.Assunto;
import Model.Disciplina;
import Model.Session;
import Principal.*;
import View.Alterar.AlterarAssunto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adria
 */
public class ConsultaAssunto extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaProfessor
     */
    public ConsultaAssunto() {
        initComponents();
        ListaTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TFPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaAssunto = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TFDiscPesquisa = new javax.swing.JTextField();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(560, 430));
        setMinimumSize(new java.awt.Dimension(560, 430));
        setPreferredSize(new java.awt.Dimension(560, 430));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 119, 36));
        jPanel1.setPreferredSize(new java.awt.Dimension(570, 73));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consulta de Assuntos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 574, 73);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Pesquisar por Assunto:");

        TFPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFPesquisaKeyReleased(evt);
            }
        });

        TabelaAssunto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Assuntos", "Disciplina"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaAssunto);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        jButton1.setToolTipText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        jButton2.setToolTipText("Ecluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Pesquisar por Disciplina");

        TFDiscPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFDiscPesquisaActionPerformed(evt);
            }
        });
        TFDiscPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFDiscPesquisaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFDiscPesquisa)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TFDiscPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 560, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
        if (TabelaAssunto.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha", title, JOptionPane.INFORMATION_MESSAGE);
        } else {
            int id = (int) TabelaAssunto.getModel().getValueAt(TabelaAssunto.getSelectedRow(), 0);
            new AssuntoDAO().deleteAssunto(id);
            ListaTable();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (TabelaAssunto.getSelectedRow() != -1) {
            int id = (int) TabelaAssunto.getModel().getValueAt(TabelaAssunto.getSelectedRow(), 0);
            Assunto as = new AssuntoDAO().getAssuntoByAssuntoId(id);
            AlterarAssunto alteraassunto = new AlterarAssunto(as);
            Principal.Desktop.add(alteraassunto);
            alteraassunto.show();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha", title, JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TFDiscPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFDiscPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFDiscPesquisaActionPerformed

    private void TFDiscPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFDiscPesquisaKeyReleased
        // TODO add your handling code here:
        ListaTable(TFPesquisa.getText(), TFDiscPesquisa.getText());
    }//GEN-LAST:event_TFDiscPesquisaKeyReleased

    private void TFPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFPesquisaKeyReleased
        // TODO add your handling code here:
        ListaTable(TFPesquisa.getText(), TFDiscPesquisa.getText());
    }//GEN-LAST:event_TFPesquisaKeyReleased

    public void ListaTable() {
        DefaultTableModel modelo = (DefaultTableModel) TabelaAssunto.getModel();

        modelo.setNumRows(0);
        AssuntoDAO assunto = new AssuntoDAO();
        int id = Session.getInstance().getUsuario().getIdUsuario();
        for (Assunto as : assunto.listarAssunto(id)) {
            modelo.addRow(new Object[]{
                as.getIdAssunto(),
                as.getNome(),
                as.getNomeDisciplina()

            });
        }
    }

    public void ListaTable(String assuntoNome, String disciplinaNome) {
        DefaultTableModel modelo = (DefaultTableModel) TabelaAssunto.getModel();

        modelo.setNumRows(0);
        AssuntoDAO assunto = new AssuntoDAO();
        int id = Session.getInstance().getUsuario().getIdUsuario();
        for (Assunto as : assunto.listarAssunto(id, assuntoNome, disciplinaNome)) {
            modelo.addRow(new Object[]{
                as.getIdAssunto(),
                as.getNome(),
                as.getNomeDisciplina()

            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFDiscPesquisa;
    private javax.swing.JTextField TFPesquisa;
    private javax.swing.JTable TabelaAssunto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
