/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Consultar;

import DAO.DisciplinaDAO;
import Model.Disciplina;
import View.Alterar.AlterarDisciplina;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adrian
 */
public class ConsultaDisciplina extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaProfessor
     */
    public ConsultaDisciplina() {
        initComponents();
        ListaTable();

    }

    public void ListaTable() {
        DefaultTableModel modelo = (DefaultTableModel) JTDisciplina.getModel();
        DisciplinaDAO discDAO = new DisciplinaDAO();
        modelo.setNumRows(0);
        for (Disciplina disc : discDAO.listarDisciplina()) {
            modelo.addRow(new Object[]{
                disc.getId(),
                disc.getDisciplina()
            });
        }

    }

    public void ListaTable(String pesquisa) {
        DefaultTableModel modelo = (DefaultTableModel) JTDisciplina.getModel();
        DisciplinaDAO discDAO = new DisciplinaDAO();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);

        }

        for (Disciplina disc : discDAO.ListarDisciplinaPorNome(pesquisa)) {
            modelo.addRow(new Object[]{
                disc.getId(),
                disc.getDisciplina()
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTDisciplina = new javax.swing.JTable();
        JBEditar = new javax.swing.JButton();
        JBExcluir = new javax.swing.JButton();
        TFDisciplina = new javax.swing.JTextField();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(490, 450));
        setMinimumSize(new java.awt.Dimension(490, 450));
        setPreferredSize(new java.awt.Dimension(490, 450));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 119, 36));
        jPanel1.setPreferredSize(new java.awt.Dimension(570, 73));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consulta de Disciplina");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 574, 73);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Pesquisar por Disciplina :");

        JTDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Disciplina"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTDisciplina);

        JBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        JBEditar.setToolTipText("Editar");
        JBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEditarActionPerformed(evt);
            }
        });

        JBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        JBExcluir.setToolTipText("Excluir");
        JBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBExcluirActionPerformed(evt);
            }
        });

        TFDisciplina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFDisciplinaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(TFDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JBExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(JBEditar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBEditar)
                    .addComponent(JBExcluir))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 580, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFDisciplinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFDisciplinaKeyReleased
        // TODO add your handling code here:
        ListaTable(TFDisciplina.getText());
    }//GEN-LAST:event_TFDisciplinaKeyReleased

    private void JBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEditarActionPerformed
        // ao clicar na linha da tabela editar o campo]
        if (JTDisciplina.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "selecione uma disciplina", "Sistema de Provas", JOptionPane.ERROR_MESSAGE);
        } else {
            int id = (int) JTDisciplina.getModel().getValueAt(JTDisciplina.getSelectedRow(), 0);
            String nomeatual = (String) JTDisciplina.getModel().getValueAt(JTDisciplina.getSelectedRow(), 1);
            AlterarDisciplina alt = new AlterarDisciplina(id, nomeatual);
            Principal.Principal.Desktop.add(alt);
            alt.show();
        }


    }//GEN-LAST:event_JBEditarActionPerformed

    private void JBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBExcluirActionPerformed
        // ao clicar na linha da tabela excluir o campo
        int linha = JTDisciplina.getSelectedRow();
        if (linha != -1) {
            Disciplina disc = new Disciplina();
            DisciplinaDAO discDAO = new DisciplinaDAO();
            disc.setId((int) JTDisciplina.getValueAt(linha, 0));

            int resposta;
            resposta = JOptionPane.showConfirmDialog(null, "Deseja excluir " + JTDisciplina.getValueAt(linha, 1) + "?");
            if (resposta == JOptionPane.YES_OPTION) {
                // verifica se o usuário clicou no botão YES
                discDAO.DeleteDisciplina(disc);
            }
            ListaTable();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma disciplina primeiro", "Sistema de Prova", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JBExcluirActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        this.ListaTable();
    }//GEN-LAST:event_formFocusGained

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        System.out.println("frame opened");
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        System.out.println("frame activated");
        this.ListaTable();
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBEditar;
    private javax.swing.JButton JBExcluir;
    private javax.swing.JTable JTDisciplina;
    private javax.swing.JTextField TFDisciplina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
