/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Consultar;

import DAO.AssuntoDAO;
import DAO.ProfessorDisciplinaDAO;
import DAO.QuestaoDAO;
import Model.Assunto;
import Model.Disciplina;
import Model.Questao;
import Model.Session;
import View.Alterar.AlterarQuestao;
import View.Alterar.AlterarQuestaoMultiplaEscolha;
import java.awt.AWTEvent;
import java.awt.Event;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adria
 */
public class ConsultaQuestao extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaProfessor
     *
     */
    public ConsultaQuestao() {
        initComponents();
        prepararCombos();
        ListaTable();
    }
    boolean recemPreparado = false;

    private void prepararCombos() {
        prepararComboDisciplina();
        prepararComboAssunto();

        recemPreparado = true;
    }

    private void prepararComboAssunto() {
        comboAssunto.removeAllItems();
        int idDisc = ((Disciplina) comboDisc.getSelectedItem()).getId();

        for (Assunto as : new AssuntoDAO().listarAssuntoByIdDisciplina(idDisc)) {
            comboAssunto.addItem(as);
        }
    }

    private void prepararComboDisciplina() {

        int id = Session.getInstance().getUsuario().getIdUsuario();

        for (Disciplina disc : new ProfessorDisciplinaDAO().ListarDisciplinaDeProfessor(id)) {
            comboDisc.addItem(disc);

        }

    }

    private void ListaTable() {
        DefaultTableModel model = (DefaultTableModel) TabelaQuestao.getModel();
        model.setNumRows(0);
        if (comboAssunto.getItemCount() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Não há itens cadastrados aqui");
            return;
        }
        int idAssunto = ((Assunto) comboAssunto.getSelectedItem()).getIdAssunto();
        List<Questao> questoes = new QuestaoDAO().listarQuestao(idAssunto);
        try {
            for (Questao q : questoes) {
                model.addRow(new Object[]{
                    q.getIdQuestao(),
                    q.getEnunciado(),
                    q.getDificuldadeString(),});
                //System.out.println(q.toString());
            }
        } catch (ArrayIndexOutOfBoundsException ex) {
            ex.printStackTrace();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JBEditar = new javax.swing.JButton();
        JBExcluir = new javax.swing.JButton();
        comboDisc = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboAssunto = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaQuestao = new javax.swing.JTable();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(580, 450));
        setMinimumSize(new java.awt.Dimension(580, 450));
        setPreferredSize(new java.awt.Dimension(580, 450));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 119, 36));
        jPanel1.setPreferredSize(new java.awt.Dimension(570, 73));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consulta de Questao");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 574, 73);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        JBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        JBEditar.setToolTipText("Excluir");
        JBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEditarActionPerformed(evt);
            }
        });

        JBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        JBExcluir.setToolTipText("Excluir");
        JBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBExcluirActionPerformed(evt);
            }
        });

        comboDisc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDiscItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Disciplina");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Assunto");

        comboAssunto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboAssuntoItemStateChanged(evt);
            }
        });

        TabelaQuestao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Enunciado", "Dificuldade"
            }
        ));
        jScrollPane2.setViewportView(TabelaQuestao);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(JBExcluir)
                            .addGap(56, 56, 56)
                            .addComponent(JBEditar))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(comboAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBExcluir)
                    .addComponent(JBEditar))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 580, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBExcluirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = TabelaQuestao.getSelectedRow();
        String valor = TabelaQuestao.getModel().getValueAt(linhaSelecionada, 0).toString();
        System.out.println(valor);
        int idquestao = Integer.valueOf(valor);
        System.out.println(idquestao);
        new QuestaoDAO().deleteQuestaoById(idquestao);
        ListaTable();

    }//GEN-LAST:event_JBExcluirActionPerformed

    private void comboDiscItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDiscItemStateChanged
        // TODO add your handling code here
//        System.out.println("state changed");
        if (!recemPreparado) {
            prepararComboAssunto();
        } else {
            recemPreparado = false;
        }
    }//GEN-LAST:event_comboDiscItemStateChanged

    private void comboAssuntoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboAssuntoItemStateChanged
        // TODO add your handling code here:
        if (comboAssunto.getSelectedIndex() != -1) {
            ListaTable();

        } else {
            DefaultTableModel model = (DefaultTableModel) TabelaQuestao.getModel();
            model.setNumRows(0);
        }
    }//GEN-LAST:event_comboAssuntoItemStateChanged

    private void JBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEditarActionPerformed
        // TODO add your handling code here:
        QuestaoDAO questdao = new QuestaoDAO();
        int linhaSelecionada = TabelaQuestao.getSelectedRow();
        String id = TabelaQuestao.getModel().getValueAt(linhaSelecionada, 0).toString();
        if (!questdao.checkIfHasItens(Integer.parseInt(id))) {
            AlterarQuestao altquest = new AlterarQuestao(Integer.parseInt(id));
            Principal.Principal.Desktop.add(altquest);
            altquest.show();

        } else {
            AlterarQuestaoMultiplaEscolha altquest = new AlterarQuestaoMultiplaEscolha(Integer.parseInt(id));
            Principal.Principal.Desktop.add(altquest);
            altquest.show();
        }


    }//GEN-LAST:event_JBEditarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        ListaTable();
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBEditar;
    private javax.swing.JButton JBExcluir;
    private javax.swing.JTable TabelaQuestao;
    private javax.swing.JComboBox<Assunto> comboAssunto;
    private javax.swing.JComboBox<Disciplina> comboDisc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
