/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Consultar;

import DAO.QuestaoDAO;
import Model.Questao;
import Model.QuestaoDescritiva;
import Model.QuestaoMultiplaEscolha;

/**
 *
 * @author professor
 */
public class ExibirProva extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     *
     * @param id
     *
     */
    int idprova;

    public ExibirProva(int id) {
        initComponents();
        idprova = id;
        colocarAsCoisasNosCantos();
    }

    private void colocarAsCoisasNosCantos() {
        String questao = "";
        String resposta = "";
        for (Questao que : new QuestaoDAO().getQuestoesIdAndNumByProvaId(idprova)) {
            questao += "\n";
            if (new QuestaoDAO().checkIfHasItens(que.getIdQuestao())) {
                QuestaoMultiplaEscolha q = new QuestaoDAO().getQuestaoMultiplaEscolha(que.getIdQuestao());
                String enunciado = q.getEnunciado();
                String[] itens = q.getItens();
                questao += que.getNumero() + ") " + enunciado + " \n";
                questao += "A) " + itens[0] + " \n";
                questao += "B) " + itens[1] + " \n";
                questao += "C) " + itens[2] + " \n";
                questao += "D) " + itens[3] + " \n";
                questao += "E) " + itens[4] + " \n";
                resposta = Character.toString(q.getGabarito());
                if (selected) {
                    for (int g = 0; g <= resposta.length() + 10; g++) {
                        questao += "_";
                    }
                    questao += "\n[Resposta:" + resposta.toUpperCase() + ")]\n";

                }
            } else {
                QuestaoDescritiva q = new QuestaoDAO().getQuestaoById(que.getIdQuestao());
                String enunciado = q.getEnunciado();
                questao += que.getNumero() + ") " + enunciado + " \n";
                resposta = q.getResposta();
                if (selected) {
                    questao += "\n";
                    questao += "[ Resposta:" + resposta + " ]\n";
                }
            }
        }

        exibirArea.setText(questao);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        exibirArea = new javax.swing.JTextArea();
        mostrarRespostaButton = new javax.swing.JToggleButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 119, 36));
        jPanel1.setPreferredSize(new java.awt.Dimension(570, 73));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Exibir Prova");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel1)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        exibirArea.setEditable(false);
        exibirArea.setColumns(20);
        exibirArea.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        exibirArea.setRows(5);
        jScrollPane1.setViewportView(exibirArea);

        mostrarRespostaButton.setText("Mostrar Resposta");
        mostrarRespostaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarRespostaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mostrarRespostaButton)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostrarRespostaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
boolean selected;
    private void mostrarRespostaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarRespostaButtonActionPerformed
        // TODO add your handling code here:
        selected = mostrarRespostaButton.isSelected();
        colocarAsCoisasNosCantos();
    }//GEN-LAST:event_mostrarRespostaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea exibirArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton mostrarRespostaButton;
    // End of variables declaration//GEN-END:variables
}
